### ISSUE TITLE
Too many sources of truth for product info

### ISSUE THREAD

**Issue by calebpeffer** [hellofirecrawl/docs#5]
Ok guys, we're running into a pretty common issue.

People are assuming that the options that exist in the playground are the only options available.

I've now had multiple customers ask for includes even though it already exists

 **They aren't going to the docs.** 

Either we need to update the playground, or maybe link to the API reference very clearly in the options field of the playground? not sure. 

@rafaelsideguide @nickscamara

**Comment by rafaelsideguide** [comment]
Added "check the docs for more options" button.
<img width="452" alt="Captura de Tela 2024-08-14 às 08 27 57" src="https://github.com/user-attachments/assets/16d3aeb2-f0f8-4115-95d6-123aca7fd66d">

I think we are now quite consistent in our documentation process, so I'm closing this for now.
