### ISSUE TITLE
Error code meanings aren't available in the API reference for crawl.

### ISSUE THREAD

**Issue by calebpeffer** [hellofirecrawl/docs#6]
<img width="786" alt="image" src="https://github.com/hellofirecrawl/docs/assets/44934913/bca922c5-8d77-4d22-a690-f330f2f56c12">

**Comment by calebpeffer** [comment]
A customer just asked about this on crisp

**Comment by rafaelsideguide** [comment]
@calebpeffer added to the updates PR:
![Image](https://github.com/user-attachments/assets/8959c22d-4fc6-496b-88e9-13fe94a679ad)

Is it ok?
