### ISSUE TITLE
It doesn't seem like we've added all the page options to /crawl 

### ISSUE THREAD

**Issue by calebpeffer** [hellofirecrawl/docs#8]
I was looking through the crawl endpoints API docs for .onlyIncludeTags, I couldn't find it, even though it was on /scrape. I think the same thing happened for the waitFor parameter.

Unless there are specific pageOptions that aren't supported on crawl, we should display these in the docs

**Comment by rafaelsideguide** [comment]
- pageOptions.onlyIncludeTags is in scrape but not in crawl
